import re

def render_schematic(circuit_data: dict, schematic_svg: str) -> str:
    """
    Validate and return the SVG generated by Gemini.
    Since Gemini drew it, it's always correct.
    """
    if schematic_svg and '<svg' in schematic_svg:
        # Ensure white background rect exists
        if 'rect' not in schematic_svg:
            schematic_svg = schematic_svg.replace(
                '<svg ',
                '<svg style="background:white" '
            )
        return schematic_svg
    
    # Fallback if SVG is missing or invalid
    return _fallback_svg(circuit_data, "SVG generation failed")

def _fallback_svg(circuit_data: dict, error: str = '') -> str:
    components   = circuit_data.get('components', [])
    circuit_name = circuit_data.get('circuit_name', 'Circuit')
    height = max(220, 100 + len(components) * 44)
    rows   = ""
    colors = ["#f0f4ff", "#fff8f0"]
    for i, comp in enumerate(components):
        y    = 110 + i * 44
        bg   = colors[i % 2]
        desc = comp.get('description', '')[:28]
        rows += (
            f'<rect x="30" y="{y-22}" width="540" height="36"'
            f' rx="5" fill="{bg}" stroke="#dde3f0"/>'
            f'<text x="50" y="{y}" font-family="Arial"'
            f' font-size="13" font-weight="bold"'
            f' fill="#333">{comp["id"]}</text>'
            f'<text x="110" y="{y}" font-family="Arial"'
            f' font-size="13" fill="#555">{comp["type"]}</text>'
            f'<text x="230" y="{y}" font-family="Arial"'
            f' font-size="13" fill="#E8520A"'
            f' font-weight="bold">{comp["value"]}</text>'
            f'<text x="340" y="{y}" font-family="Arial"'
            f' font-size="11" fill="#777">{desc}</text>'
        )
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg"'
        f' width="600" height="{height}">'
        f'<rect width="600" height="{height}"'
        f' fill="white" rx="8"/>'
        f'<text x="300" y="38" text-anchor="middle"'
        f' font-family="Arial" font-size="17"'
        f' font-weight="bold" fill="#1a1a1a">'
        f'{circuit_name}</text>'
        f'<line x1="30" y1="74" x2="570" y2="74"'
        f' stroke="#E8520A" stroke-width="2"/>'
        f'{rows}</svg>'
    )
